# Generated by Django 2.2.4 on 2019-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='user_num')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='user name')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='register time')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'ssers',
                'db_table': 'tb_user',
            },
        ),
    ]
